on: [push, pull_request]
name: CI

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        name:
          [
            btor,
            cvc5,
            msat,
            yices2,
            z3
          ]

        include:
          - name: msat
            setup_opts: --auto-yes

    name: ${{ matrix.os }}:${{ matrix.name }} 
    runs-on: ${{ matrix.os}}

    steps:
      - uses: actions/checkout@v2

      - name: Install Packages (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            gperf \
            libgmp-dev \
            openjdk-8-jdk

      - name: Install Packages (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install \
            gmp \
            gperf

      - name: Python Dependencies
        run: |
          python3 -m pip install --user Cython==0.29.*
          python3 -m pip install --user pytest scikit-build toml pyparsing
          echo "$(python3 -m site --user-base)/bin" >> $GITHUB_PATH

      - name: Install Bison
        run: ./contrib/setup-bison.sh

      - name: Install Flex (macOS)
        if: runner.os == 'macOS'
        run: ./contrib/setup-flex.sh

      - name: Setup Underlying Solver
        run: ./ci-scripts/setup-${{ matrix.name }}.sh ${{ matrix.setup_opts }}

      - name: Configure
        run: ./configure.sh --${{ matrix.name }} --debug --python --smtlib-reader

      - name: Build
        run: |
          cd build
          make -j

      - name: Test C++
        run: |
          cd build
          make test

      - name: Install Python Bindings
        run: python3 -m pip install --user -e ./build/python[test,pysmt]

      - name: Test Python Bindings
        run: pytest ./tests
